### ISSUE TITLE
Position of the popup is not correct

### ISSUE THREAD

**Issue by ayox** [Semantic-Org/UI-Popup#2]
I have a problem with the position of the popup when I have it on multiple rows inside a table using 2.2.11. I don't have this problem on version 2.2.3. Thanks

**Comment by bryanbuchs** [comment]
I had the same issue, but not limited to table rows -- although I am using it in a table as well.

It's not included in the popup.css, but I backtracked and found a rule in site.css (from the full package) that needed to be included.

`
html,
body {
    height: 100%;
}
`
